2019-11-27 20:11:44,332 - root - INFO - ** Kedro project homelesslink
2019-11-27 20:11:44,332 - root - INFO - Defined global variable `context` and `catalog`
2019-11-27 20:12:30,928 - root - INFO - ** Kedro project homelesslink
2019-11-27 20:12:30,928 - root - INFO - Defined global variable `context` and `catalog`
2019-11-27 20:12:46,511 - root - INFO - ** Kedro project homelesslink
2019-11-27 20:12:46,512 - root - INFO - Defined global variable `context` and `catalog`
2019-11-27 20:12:53,765 - kedro.io.data_catalog - INFO - Loading data from `example_iris_data2` (CSVLocalDataSet)...
2019-11-27 20:14:46,179 - root - INFO - ** Kedro project homelesslink
2019-11-27 20:14:46,179 - root - INFO - Defined global variable `context` and `catalog`
2019-11-27 20:15:12,038 - kedro.io.data_catalog - INFO - Loading data from `params:inside_parameter` (MemoryDataSet)...
2019-11-27 20:17:41,395 - root - INFO - ** Kedro project homelesslink
2019-11-27 20:17:41,396 - root - INFO - Defined global variable `context` and `catalog`
2019-11-27 20:18:14,386 - root - INFO - ** Kedro project homelesslink
2019-11-27 20:18:14,403 - kedro.versioning.journal - WARNING - Unable to git describe /Users/sheldon_tsen/Projects/HomessLink/tech4good/homelesslink
2019-11-27 20:18:14,435 - kedro.io.data_catalog - INFO - Loading data from `example_iris_data` (CSVLocalDataSet)...
2019-11-27 20:18:14,444 - kedro.io.data_catalog - INFO - Loading data from `params:example_test_data_ratio` (MemoryDataSet)...
2019-11-27 20:18:14,444 - kedro.pipeline.node - INFO - Running node: split_data([example_iris_data,params:example_test_data_ratio]) -> [example_test_x,example_test_y,example_train_x,example_train_y]
2019-11-27 20:18:14,458 - kedro.io.data_catalog - INFO - Saving data to `example_train_x` (MemoryDataSet)...
2019-11-27 20:18:14,458 - kedro.io.data_catalog - INFO - Saving data to `example_train_y` (MemoryDataSet)...
2019-11-27 20:18:14,459 - kedro.io.data_catalog - INFO - Saving data to `example_test_x` (MemoryDataSet)...
2019-11-27 20:18:14,459 - kedro.io.data_catalog - INFO - Saving data to `example_test_y` (MemoryDataSet)...
2019-11-27 20:18:14,460 - kedro.runner.sequential_runner - INFO - Completed 1 out of 4 tasks
2019-11-27 20:18:14,460 - kedro.io.data_catalog - INFO - Loading data from `example_train_x` (MemoryDataSet)...
2019-11-27 20:18:14,460 - kedro.io.data_catalog - INFO - Loading data from `example_train_y` (MemoryDataSet)...
2019-11-27 20:18:14,460 - kedro.io.data_catalog - INFO - Loading data from `parameters` (MemoryDataSet)...
2019-11-27 20:18:14,460 - kedro.pipeline.node - INFO - Running node: train_model([example_train_x,example_train_y,parameters]) -> [example_model]
2019-11-27 20:18:14,780 - kedro.io.data_catalog - INFO - Saving data to `example_model` (MemoryDataSet)...
2019-11-27 20:18:14,781 - kedro.runner.sequential_runner - INFO - Completed 2 out of 4 tasks
2019-11-27 20:18:14,781 - kedro.io.data_catalog - INFO - Loading data from `example_model` (MemoryDataSet)...
2019-11-27 20:18:14,781 - kedro.io.data_catalog - INFO - Loading data from `example_test_x` (MemoryDataSet)...
2019-11-27 20:18:14,781 - kedro.pipeline.node - INFO - Running node: predict([example_model,example_test_x]) -> [example_predictions]
2019-11-27 20:18:14,781 - kedro.io.data_catalog - INFO - Saving data to `example_predictions` (MemoryDataSet)...
2019-11-27 20:18:14,782 - kedro.runner.sequential_runner - INFO - Completed 3 out of 4 tasks
2019-11-27 20:18:14,782 - kedro.io.data_catalog - INFO - Loading data from `example_predictions` (MemoryDataSet)...
2019-11-27 20:18:14,782 - kedro.io.data_catalog - INFO - Loading data from `example_test_y` (MemoryDataSet)...
2019-11-27 20:18:14,782 - kedro.pipeline.node - INFO - Running node: report_accuracy([example_predictions,example_test_y]) -> None
2019-11-27 20:18:14,782 - homelesslink.pipelines.data_science.nodes.nodes - INFO - Model accuracy on test set: 96.67%
2019-11-27 20:18:14,783 - kedro.runner.sequential_runner - INFO - Completed 4 out of 4 tasks
2019-11-27 20:18:14,783 - kedro.runner.sequential_runner - INFO - Pipeline execution completed successfully.
2019-11-27 20:24:30,075 - root - ERROR - Kedro's ipython session startup script failed:
Java gateway process exited before sending its port number
Traceback (most recent call last):
  File "/Users/sheldon_tsen/Projects/HomessLink/tech4good/homelesslink/.ipython/profile_default/startup/00-kedro-init.py", line 33, in reload_kedro
    context = load_context(path)
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/kedro/context/context.py", line 525, in load_context
    context = context_class(project_path, **kwargs)
  File "/Users/sheldon_tsen/Projects/HomessLink/tech4good/homelesslink/src/homelesslink/run.py", line 64, in __init__
    self.init_spark_session()
  File "/Users/sheldon_tsen/Projects/HomessLink/tech4good/homelesslink/src/homelesslink/run.py", line 82, in init_spark_session
    self._spark_session = spark_session_conf.master("yarn").getOrCreate()
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/pyspark/sql/session.py", line 173, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/pyspark/context.py", line 367, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/pyspark/context.py", line 133, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/pyspark/context.py", line 316, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/pyspark/java_gateway.py", line 46, in launch_gateway
    return _launch_gateway(conf)
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/pyspark/java_gateway.py", line 108, in _launch_gateway
    raise Exception("Java gateway process exited before sending its port number")
Exception: Java gateway process exited before sending its port number
2019-11-27 20:25:12,241 - root - ERROR - Kedro's ipython session startup script failed:
Java gateway process exited before sending its port number
Traceback (most recent call last):
  File "/Users/sheldon_tsen/Projects/HomessLink/tech4good/homelesslink/.ipython/profile_default/startup/00-kedro-init.py", line 33, in reload_kedro
    context = load_context(path)
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/kedro/context/context.py", line 525, in load_context
    context = context_class(project_path, **kwargs)
  File "/Users/sheldon_tsen/Projects/HomessLink/tech4good/homelesslink/src/homelesslink/run.py", line 64, in __init__
    self.init_spark_session()
  File "/Users/sheldon_tsen/Projects/HomessLink/tech4good/homelesslink/src/homelesslink/run.py", line 82, in init_spark_session
    self._spark_session = spark_session_conf.master("yarn").getOrCreate()
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/pyspark/sql/session.py", line 173, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/pyspark/context.py", line 367, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/pyspark/context.py", line 133, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/pyspark/context.py", line 316, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/pyspark/java_gateway.py", line 46, in launch_gateway
    return _launch_gateway(conf)
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/pyspark/java_gateway.py", line 108, in _launch_gateway
    raise Exception("Java gateway process exited before sending its port number")
Exception: Java gateway process exited before sending its port number
2019-11-27 20:25:31,653 - homelesslink.run - INFO - parameters: {'spark.driver.memory': '6g'}
2019-11-27 20:25:32,388 - root - ERROR - Kedro's ipython session startup script failed:
Java gateway process exited before sending its port number
Traceback (most recent call last):
  File "/Users/sheldon_tsen/Projects/HomessLink/tech4good/homelesslink/.ipython/profile_default/startup/00-kedro-init.py", line 33, in reload_kedro
    context = load_context(path)
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/kedro/context/context.py", line 525, in load_context
    context = context_class(project_path, **kwargs)
  File "/Users/sheldon_tsen/Projects/HomessLink/tech4good/homelesslink/src/homelesslink/run.py", line 64, in __init__
    self.init_spark_session()
  File "/Users/sheldon_tsen/Projects/HomessLink/tech4good/homelesslink/src/homelesslink/run.py", line 83, in init_spark_session
    self._spark_session = spark_session_conf.master("yarn").getOrCreate()
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/pyspark/sql/session.py", line 173, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/pyspark/context.py", line 367, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/pyspark/context.py", line 133, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/pyspark/context.py", line 316, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/pyspark/java_gateway.py", line 46, in launch_gateway
    return _launch_gateway(conf)
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/pyspark/java_gateway.py", line 108, in _launch_gateway
    raise Exception("Java gateway process exited before sending its port number")
Exception: Java gateway process exited before sending its port number
2019-11-27 20:25:57,266 - homelesslink.run - INFO - parameters: {'spark.driver.memory': '6g'}
2019-11-27 20:26:01,090 - root - INFO - ** Kedro project homelesslink
2019-11-27 20:26:01,091 - root - INFO - Defined global variable `context` and `catalog`
2019-11-27 20:27:12,942 - homelesslink.run - INFO - parameters: {'spark.driver.memory': '6g'}
2019-11-27 20:27:13,674 - root - ERROR - Kedro's ipython session startup script failed:
Java gateway process exited before sending its port number
Traceback (most recent call last):
  File "/Users/sheldon_tsen/Projects/HomessLink/tech4good/homelesslink/.ipython/profile_default/startup/00-kedro-init.py", line 33, in reload_kedro
    context = load_context(path)
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/kedro/context/context.py", line 525, in load_context
    context = context_class(project_path, **kwargs)
  File "/Users/sheldon_tsen/Projects/HomessLink/tech4good/homelesslink/src/homelesslink/run.py", line 64, in __init__
    self.init_spark_session()
  File "/Users/sheldon_tsen/Projects/HomessLink/tech4good/homelesslink/src/homelesslink/run.py", line 83, in init_spark_session
    self._spark = spark_session_conf.master("yarn").getOrCreate()
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/pyspark/sql/session.py", line 173, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/pyspark/context.py", line 367, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/pyspark/context.py", line 133, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/pyspark/context.py", line 316, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/pyspark/java_gateway.py", line 46, in launch_gateway
    return _launch_gateway(conf)
  File "/anaconda3/envs/homelesslink/lib/python3.6/site-packages/pyspark/java_gateway.py", line 108, in _launch_gateway
    raise Exception("Java gateway process exited before sending its port number")
Exception: Java gateway process exited before sending its port number
2019-11-27 20:27:50,961 - homelesslink.run - INFO - parameters: {'spark.driver.memory': '6g'}
2019-11-27 20:27:53,502 - homelesslink.run - INFO - ** Spark session created with following config:
2019-11-27 20:27:53,508 - root - INFO - ('spark.app.id', 'local-1574886472781')
2019-11-27 20:27:53,508 - root - INFO - ('spark.app.name', 'homelesslink_sheldon_tsen')
2019-11-27 20:27:53,508 - root - INFO - ('spark.driver.host', 'ip-192-168-1-103.eu-west-2.compute.internal')
2019-11-27 20:27:53,508 - root - INFO - ('spark.driver.memory', '6g')
2019-11-27 20:27:53,508 - root - INFO - ('spark.driver.port', '55621')
2019-11-27 20:27:53,508 - root - INFO - ('spark.executor.id', 'driver')
2019-11-27 20:27:53,508 - root - INFO - ('spark.master', 'local[*]')
2019-11-27 20:27:53,508 - root - INFO - ('spark.rdd.compress', 'True')
2019-11-27 20:27:53,508 - root - INFO - ('spark.serializer.objectStreamReset', '100')
2019-11-27 20:27:53,509 - root - INFO - ('spark.sql.catalogImplementation', 'hive')
2019-11-27 20:27:53,509 - root - INFO - ('spark.submit.deployMode', 'client')
2019-11-27 20:27:53,509 - root - INFO - ('spark.ui.showConsoleProgress', 'true')
2019-11-27 20:27:53,510 - homelesslink.run - INFO - SparkUI at: http://ip-192-168-1-103.eu-west-2.compute.internal:4040
2019-11-27 20:27:53,536 - root - INFO - ** Kedro project homelesslink
2019-11-27 20:27:53,537 - root - INFO - Defined global variable `context` and `catalog`
2019-11-27 20:29:19,888 - homelesslink.run - INFO - parameters: {'spark.driver.memory': '6g'}
2019-11-27 20:29:23,000 - homelesslink.run - INFO - ** Spark session created with following config:
2019-11-27 20:29:23,007 - root - INFO - ('spark.app.id', 'local-1574886562043')
2019-11-27 20:29:23,007 - root - INFO - ('spark.app.name', 'homelesslink_sheldon_tsen')
2019-11-27 20:29:23,007 - root - INFO - ('spark.driver.host', 'ip-192-168-1-103.eu-west-2.compute.internal')
2019-11-27 20:29:23,007 - root - INFO - ('spark.driver.memory', '6g')
2019-11-27 20:29:23,007 - root - INFO - ('spark.driver.port', '55710')
2019-11-27 20:29:23,008 - root - INFO - ('spark.executor.id', 'driver')
2019-11-27 20:29:23,008 - root - INFO - ('spark.master', 'local[*]')
2019-11-27 20:29:23,008 - root - INFO - ('spark.rdd.compress', 'True')
2019-11-27 20:29:23,008 - root - INFO - ('spark.serializer.objectStreamReset', '100')
2019-11-27 20:29:23,008 - root - INFO - ('spark.sql.catalogImplementation', 'hive')
2019-11-27 20:29:23,008 - root - INFO - ('spark.submit.deployMode', 'client')
2019-11-27 20:29:23,008 - root - INFO - ('spark.ui.showConsoleProgress', 'true')
2019-11-27 20:29:23,010 - homelesslink.run - INFO - SparkUI at: http://ip-192-168-1-103.eu-west-2.compute.internal:4040
2019-11-27 20:29:23,036 - root - INFO - ** Kedro project homelesslink
2019-11-27 20:29:23,037 - root - INFO - Defined global variable `context` and `catalog`
2019-11-27 20:29:36,093 - kedro.io.data_catalog - INFO - Loading data from `example_iris_data` (CSVLocalDataSet)...
2019-11-27 20:29:37,431 - kedro.io.data_catalog - INFO - Loading data from `example_iris_data` (CSVLocalDataSet)...
